#!/usr/bin/env bash
# ============================================================
# collect.sh — Sync ~/.config + a few home files into this repo.
#
# Data-driven: the lists below name exactly what we want tracked.
# Edit those when you adopt or drop a tool.
#
# Run from anywhere:   bash /path/to/collect.sh
# ============================================================
set -eu

DOTFILES_DIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
CONFIG_OUT="$DOTFILES_DIR/config"
HOME_OUT="$DOTFILES_DIR/home"

# --- What we track --------------------------------------------------------
#
# Anything not listed here is ignored. Things to NOT track:
#   - per-app dirs that the app rewrites on every run (Code, discord,
#     mozilla, htop, mpv, pulse, systemd, Thunar, xfce4, …)
#   - autogenerated state (~/.cache, /tmp, lock files)

CONFIG_DIRS=(
    hypr
    kitty
    wofi
    dunst
    eww
    profiles
    dotfiles-cli
    matugen
    networkmanager-dmenu
    nwg-look
    fastfetch
    xsettingsd
    gtk-3.0
    gtk-4.0
)

CONFIG_FILES=(
    mimeapps.list
)

# Files / dirs under $HOME (not inside .config).
HOME_FILES=(
    .gtkrc-2.0
)

HOME_DIRS=(
    .icons/default
)

# --- Per-tree exclude patterns (regex passed to rsync --exclude) ----------
#
# Each pair: <tree-name>:<glob> — only applied when copying that tree.

EXCLUDES=(
    # don't ship the prayer venv that gets regenerated on demand
    "eww:scripts/.venv"
    "eww:scripts/__pycache__"
    "eww:scripts/*.pyc"

    # profiles can be regenerated; drop any local lock/state files
    "profiles:.current"
    "profiles:.current.lock"

    # personal wallpaper images — too big and personal for git;
    # the profile system + split-wallpaper.sh / set-wallpaper.sh handle
    # restoring them locally from ~/Pictures.
    "profiles:**/wallpapers"

    # python caches everywhere
    "*:**/__pycache__"
    "*:**/*.pyc"
)

# --------------------------------------------------------------------------
say() { printf '  %s\n' "$*"; }
ok()  { say "✓ $*"; }
skip(){ say "· $* (missing — skipped)"; }

echo "==> Collecting dotfiles into $DOTFILES_DIR"
echo

mkdir -p "$CONFIG_OUT" "$HOME_OUT"

# Glob patterns for one tree (tree-specific + universal "*:" pairs).
excludes_for() {
    local tree="$1"
    local pair
    local -a globs=()
    for pair in "${EXCLUDES[@]}"; do
        case "$pair" in
            "$tree:"*|"*:"*) globs+=("${pair#*:}") ;;
        esac
    done
    printf '%s\n' "${globs[@]}"
}

# Prune paths inside <dst> that match any exclude glob. Globs use bash
# extglob so patterns like ** and *.pyc work naturally.
prune_excluded() {
    local dst="$1" name="$2"
    mapfile -t globs < <(excludes_for "$name")
    [ "${#globs[@]}" -eq 0 ] && return
    shopt -s globstar nullglob
    local g hit
    for g in "${globs[@]}"; do
        for hit in "$dst"/$g; do
            [ -e "$hit" ] || continue
            rm -rf -- "$hit"
        done
    done
    shopt -u globstar nullglob
}

copy_tree() {
    # copy_tree <src> <dst> <tree-name>
    local src="$1" dst="$2" name="$3"
    [ -d "$src" ] || { skip "$name"; return; }
    rm -rf -- "$dst"
    mkdir -p "$dst"
    # cp -a preserves perms / symlinks / timestamps. The trailing /. tells
    # cp to copy the contents (not the dir itself).
    cp -a "$src/." "$dst/"
    prune_excluded "$dst" "$name"
    ok "$name"
}

copy_file() {
    local src="$1" dst="$2" label="$3"
    if [ -f "$src" ]; then
        mkdir -p "$(dirname "$dst")"
        cp -f "$src" "$dst"
        ok "$label"
    else
        skip "$label"
    fi
}

echo "── ~/.config dirs ──"
for d in "${CONFIG_DIRS[@]}"; do
    copy_tree "$HOME/.config/$d" "$CONFIG_OUT/$d" "$d"
done

echo
echo "── ~/.config files ──"
for f in "${CONFIG_FILES[@]}"; do
    copy_file "$HOME/.config/$f" "$CONFIG_OUT/$f" "$f"
done

echo
echo "── \$HOME files ──"
for f in "${HOME_FILES[@]}"; do
    copy_file "$HOME/$f" "$HOME_OUT/$f" "$f"
done

echo
echo "── \$HOME dirs ──"
for d in "${HOME_DIRS[@]}"; do
    copy_tree "$HOME/$d" "$HOME_OUT/$d" "$d"
done

echo
echo "── Package snapshot ──"
pacman -Qqe > "$DOTFILES_DIR/packages.txt"
pacman -Qqem > "$DOTFILES_DIR/packages-aur.txt"
cp "$DOTFILES_DIR/packages.txt" "$DOTFILES_DIR/.last-packages.txt"
ok "packages.txt + packages-aur.txt"

echo
echo "==> Done."
echo "    cd $DOTFILES_DIR && git status"
