splash = false

preload = /home/hsdehaini/Pictures/wallpapers/escape_velocity_0.png
preload = /home/hsdehaini/Pictures/wallpapers/escape_velocity_1.png

wallpaper {
    monitor = DP-3
    path = /home/hsdehaini/Pictures/wallpapers/escape_velocity_0.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-2
    path = /home/hsdehaini/Pictures/wallpapers/escape_velocity_1.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/hsdehaini/Pictures/wallpapers/space-sky.png
    fit_mode = cover
}
