preload = /home/hsdehaini/Pictures/wallpapers/ultrawide-galaxy-0.png
preload = /home/hsdehaini/Pictures/wallpapers/ultrawide-galaxy-1.png

wallpaper {
    monitor = DP-3
    path = /home/hsdehaini/Pictures/wallpapers/ultrawide-galaxy-0.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-2
    path = /home/hsdehaini/Pictures/wallpapers/ultrawide-galaxy-1.png
    fit_mode = cover
}
